import Header from '@/component/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <div>
          <h2>Site voitures</h2>
        </div>
      <body className={inter.className}>
        <Header />
        {children}
        </body>
      <div>
        <h2>footer</h2>
        <p>les horaires</p>
      </div>
    </html>
  )
}
