// pages\Home\index.js:

// import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import Entretien from './Entretien'
import Footer from './Footer'
import Header from './Header'
import AppointmentForm from './AppointmentForm'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        <Entretien />
        <AppointmentForm />
        {children}
        </body>
      <div>
        <Footer />
      </div>
    </html>
  )
}


















