// pages/Home/index.js
import Head from 'next/head'
import Entretien from '../Entretien'
import Footer from '../../Componente/Footer'
import Header from '../../Componente/Header'
import AppointmentForm from '../AppointmentForm'
import SomeComponent from '../Second-handGallery'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Garage V-Parrot</title>
      </Head>
      <Header />
      <Entretien />
      <SomeComponent />
      <AppointmentForm />
      {children}
      <Footer />
    </>
  )
}

  















